"""add Meta daily coverage

Revision ID: 0310728884dd
Revises: 0409b0068de9
Create Date: 2026-09-29 08:44:39.241689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0310728884dd'
down_revision: Union[str, Sequence[str], None] = '0409b0068de9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta_daily_coverage',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ad_account_id', sa.String(length=50), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ad_account_id', 'report_date', name='uq_meta_daily_coverage_account_date')
    )
    op.create_index(op.f('ix_meta_daily_coverage_ad_account_id'), 'meta_daily_coverage', ['ad_account_id'], unique=False)
    op.create_index(op.f('ix_meta_daily_coverage_report_date'), 'meta_daily_coverage', ['report_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meta_daily_coverage_report_date'), table_name='meta_daily_coverage')
    op.drop_index(op.f('ix_meta_daily_coverage_ad_account_id'), table_name='meta_daily_coverage')
    op.drop_table('meta_daily_coverage')
    # ### end Alembic commands ###
