"""add Meta daily spend

Revision ID: 0409b0068de9
Revises: 305504125cd9
Create Date: 2026-09-28 15:59:14.799907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0409b0068de9'
down_revision: Union[str, Sequence[str], None] = '305504125cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta_daily_spend',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ad_account_id', sa.String(length=50), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('spend', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('impressions', sa.BigInteger(), nullable=False),
    sa.Column('clicks', sa.BigInteger(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ad_account_id', 'report_date', name='uq_meta_daily_spend_account_date')
    )
    op.create_index(op.f('ix_meta_daily_spend_ad_account_id'), 'meta_daily_spend', ['ad_account_id'], unique=False)
    op.create_index(op.f('ix_meta_daily_spend_report_date'), 'meta_daily_spend', ['report_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meta_daily_spend_report_date'), table_name='meta_daily_spend')
    op.drop_index(op.f('ix_meta_daily_spend_ad_account_id'), table_name='meta_daily_spend')
    op.drop_table('meta_daily_spend')
    # ### end Alembic commands ###
