"""preserve Everflow monetary precision

Revision ID: 2d6a9c26295c
Revises: 6d25c89beb7c
Create Date: 2026-09-29 17:55:51.578782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d6a9c26295c'
down_revision: Union[str, Sequence[str], None] = '6d25c89beb7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('everflow_daily_performance', 'payout',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    op.alter_column('everflow_daily_performance', 'revenue',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    op.alter_column('everflow_daily_performance', 'gross_sales',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('everflow_daily_performance', 'gross_sales',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('everflow_daily_performance', 'revenue',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('everflow_daily_performance', 'payout',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=14, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
