"""add manual marketing spend

Revision ID: 305504125cd9
Revises: 6092a7f5551e
Create Date: 2026-09-26 09:09:49.399902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '305504125cd9'
down_revision: Union[str, Sequence[str], None] = '6092a7f5551e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_spend',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('record_id', sa.String(length=100), nullable=False),
    sa.Column('vendor', sa.String(length=200), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=False),
    sa.Column('campaign', sa.String(length=300), nullable=True),
    sa.Column('cost_type', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('service_start_date', sa.Date(), nullable=False),
    sa.Column('service_end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('reference', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_spend_record_id'), 'manual_spend', ['record_id'], unique=True)
    op.create_index(op.f('ix_manual_spend_service_end_date'), 'manual_spend', ['service_end_date'], unique=False)
    op.create_index(op.f('ix_manual_spend_service_start_date'), 'manual_spend', ['service_start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manual_spend_service_start_date'), table_name='manual_spend')
    op.drop_index(op.f('ix_manual_spend_service_end_date'), table_name='manual_spend')
    op.drop_index(op.f('ix_manual_spend_record_id'), table_name='manual_spend')
    op.drop_table('manual_spend')
    # ### end Alembic commands ###
