"""add unallocated refund amount

Revision ID: 4acde16f235b
Revises: 7de81e89a3af
Create Date: 2026-09-24 17:15:53.055162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4acde16f235b'
down_revision: Union[str, Sequence[str], None] = '7de81e89a3af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refunds', sa.Column('unallocated_refund_amount', sa.Numeric(precision=14, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refunds', 'unallocated_refund_amount')
    # ### end Alembic commands ###
