"""create core commerce tables

Revision ID: 7de81e89a3af
Revises: 
Create Date: 2026-09-24 16:14:02.285172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7de81e89a3af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('shopify_customer_id', sa.String(length=100), nullable=False),
    sa.Column('shopify_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shopify_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_shopify_customer_id'), 'customers', ['shopify_customer_id'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('shopify_order_id', sa.String(length=100), nullable=False),
    sa.Column('shopify_order_name', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('has_successful_payment', sa.Boolean(), nullable=False),
    sa.Column('display_financial_status', sa.String(length=40), nullable=True),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('product_revenue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('shipping_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_charged', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('shopify_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_processed_at'), 'orders', ['processed_at'], unique=False)
    op.create_index(op.f('ix_orders_shopify_order_id'), 'orders', ['shopify_order_id'], unique=True)
    op.create_table('order_lines',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('shopify_line_item_id', sa.String(length=100), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('shopify_product_id', sa.String(length=100), nullable=True),
    sa.Column('shopify_variant_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('gross_product_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('product_revenue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_lines_order_id'), 'order_lines', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_lines_shopify_line_item_id'), 'order_lines', ['shopify_line_item_id'], unique=True)
    op.create_table('refunds',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('shopify_refund_id', sa.String(length=100), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('product_refund_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('shipping_refund_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_refund_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fee_refund_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_refund_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_created_at'), 'refunds', ['created_at'], unique=False)
    op.create_index(op.f('ix_refunds_order_id'), 'refunds', ['order_id'], unique=False)
    op.create_index(op.f('ix_refunds_shopify_refund_id'), 'refunds', ['shopify_refund_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refunds_shopify_refund_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_order_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_created_at'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_order_lines_shopify_line_item_id'), table_name='order_lines')
    op.drop_index(op.f('ix_order_lines_order_id'), table_name='order_lines')
    op.drop_table('order_lines')
    op.drop_index(op.f('ix_orders_shopify_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_processed_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_customers_shopify_customer_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
