"""add ThoughtMetric daily attribution

Revision ID: 8fe36407f94d
Revises: 2d6a9c26295c
Create Date: 2026-09-30 17:51:30.003167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fe36407f94d'
down_revision: Union[str, Sequence[str], None] = '2d6a9c26295c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thoughtmetric_daily_channel',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('channel_key', sa.String(length=100), nullable=False),
    sa.Column('orders', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('new_customer_orders', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('new_customer_sales', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('attributed_total_sales', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('converted_spend', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_date', 'channel_key', name='uq_thoughtmetric_daily_channel_date_key')
    )
    op.create_index(op.f('ix_thoughtmetric_daily_channel_channel_key'), 'thoughtmetric_daily_channel', ['channel_key'], unique=False)
    op.create_index(op.f('ix_thoughtmetric_daily_channel_report_date'), 'thoughtmetric_daily_channel', ['report_date'], unique=False)
    op.create_table('thoughtmetric_daily_coverage',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thoughtmetric_daily_coverage_report_date'), 'thoughtmetric_daily_coverage', ['report_date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thoughtmetric_daily_coverage_report_date'), table_name='thoughtmetric_daily_coverage')
    op.drop_table('thoughtmetric_daily_coverage')
    op.drop_index(op.f('ix_thoughtmetric_daily_channel_report_date'), table_name='thoughtmetric_daily_channel')
    op.drop_index(op.f('ix_thoughtmetric_daily_channel_channel_key'), table_name='thoughtmetric_daily_channel')
    op.drop_table('thoughtmetric_daily_channel')
    # ### end Alembic commands ###
