"""add order provenance and reporting dates

Revision ID: 96c9bba4cfa2
Revises: 4acde16f235b
Create Date: 2026-09-24 23:03:08.985673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96c9bba4cfa2'
down_revision: Union[str, Sequence[str], None] = '4acde16f235b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('woo_customer_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_customers_woo_customer_id'), 'customers', ['woo_customer_id'], unique=False)
    op.add_column('orders', sa.Column('shopify_created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('reporting_order_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('source_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('source_system', sa.String(length=40), nullable=True))
    op.add_column('orders', sa.Column('source_order_id', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('woo_customer_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_orders_reporting_order_at'), 'orders', ['reporting_order_at'], unique=False)
    op.create_index(op.f('ix_orders_source_order_id'), 'orders', ['source_order_id'], unique=False)
    op.create_index(op.f('ix_orders_source_system'), 'orders', ['source_system'], unique=False)
    op.create_index(op.f('ix_orders_woo_customer_id'), 'orders', ['woo_customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_woo_customer_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_source_system'), table_name='orders')
    op.drop_index(op.f('ix_orders_source_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_reporting_order_at'), table_name='orders')
    op.drop_column('orders', 'woo_customer_id')
    op.drop_column('orders', 'source_order_id')
    op.drop_column('orders', 'source_system')
    op.drop_column('orders', 'source_name')
    op.drop_column('orders', 'reporting_order_at')
    op.drop_column('orders', 'shopify_created_at')
    op.drop_index(op.f('ix_customers_woo_customer_id'), table_name='customers')
    op.drop_column('customers', 'woo_customer_id')
    # ### end Alembic commands ###
