"""Add Appstle subscription tables

Revision ID: b6fa85610973
Revises: 8fe36407f94d
Create Date: 2026-10-03 07:25:16.819717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6fa85610973'
down_revision: Union[str, Sequence[str], None] = '8fe36407f94d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appstle_subscription_contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.String(length=64), nullable=False),
    sa.Column('shopify_customer_id', sa.String(length=64), nullable=False),
    sa.Column('shopify_customer_gid', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_billing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_shopify_order_id', sa.String(length=128), nullable=True),
    sa.Column('origin_order_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_link_method', sa.String(length=32), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appstle_subscription_contract_contract_id'), 'appstle_subscription_contract', ['contract_id'], unique=True)
    op.create_index(op.f('ix_appstle_subscription_contract_origin_shopify_order_id'), 'appstle_subscription_contract', ['origin_shopify_order_id'], unique=False)
    op.create_index(op.f('ix_appstle_subscription_contract_shopify_customer_gid'), 'appstle_subscription_contract', ['shopify_customer_gid'], unique=False)
    op.create_index(op.f('ix_appstle_subscription_contract_shopify_customer_id'), 'appstle_subscription_contract', ['shopify_customer_id'], unique=False)
    op.create_index(op.f('ix_appstle_subscription_contract_status'), 'appstle_subscription_contract', ['status'], unique=False)
    op.create_table('appstle_subscription_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appstle_row_id', sa.BigInteger(), nullable=False),
    sa.Column('contract_id', sa.String(length=64), nullable=False),
    sa.Column('billing_attempt_id', sa.String(length=160), nullable=True),
    sa.Column('billing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('shopify_order_id', sa.String(length=128), nullable=True),
    sa.Column('shopify_order_name', sa.String(length=64), nullable=True),
    sa.Column('order_amount', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('order_amount_usd', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('order_processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appstle_subscription_order_appstle_row_id'), 'appstle_subscription_order', ['appstle_row_id'], unique=True)
    op.create_index(op.f('ix_appstle_subscription_order_billing_attempt_id'), 'appstle_subscription_order', ['billing_attempt_id'], unique=False)
    op.create_index(op.f('ix_appstle_subscription_order_contract_id'), 'appstle_subscription_order', ['contract_id'], unique=False)
    op.create_index(op.f('ix_appstle_subscription_order_shopify_order_id'), 'appstle_subscription_order', ['shopify_order_id'], unique=False)
    op.create_index(op.f('ix_appstle_subscription_order_status'), 'appstle_subscription_order', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appstle_subscription_order_status'), table_name='appstle_subscription_order')
    op.drop_index(op.f('ix_appstle_subscription_order_shopify_order_id'), table_name='appstle_subscription_order')
    op.drop_index(op.f('ix_appstle_subscription_order_contract_id'), table_name='appstle_subscription_order')
    op.drop_index(op.f('ix_appstle_subscription_order_billing_attempt_id'), table_name='appstle_subscription_order')
    op.drop_index(op.f('ix_appstle_subscription_order_appstle_row_id'), table_name='appstle_subscription_order')
    op.drop_table('appstle_subscription_order')
    op.drop_index(op.f('ix_appstle_subscription_contract_status'), table_name='appstle_subscription_contract')
    op.drop_index(op.f('ix_appstle_subscription_contract_shopify_customer_id'), table_name='appstle_subscription_contract')
    op.drop_index(op.f('ix_appstle_subscription_contract_shopify_customer_gid'), table_name='appstle_subscription_contract')
    op.drop_index(op.f('ix_appstle_subscription_contract_origin_shopify_order_id'), table_name='appstle_subscription_contract')
    op.drop_index(op.f('ix_appstle_subscription_contract_contract_id'), table_name='appstle_subscription_contract')
    op.drop_table('appstle_subscription_contract')
    # ### end Alembic commands ###
