"""Support Appstle orders without row ids

Revision ID: cf95fceb434d
Revises: b6fa85610973
Create Date: 2026-10-03 08:14:00.194585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf95fceb434d'
down_revision: Union[str, Sequence[str], None] = 'b6fa85610973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "appstle_subscription_order",
        sa.Column(
            "source_key",
            sa.String(length=200),
            nullable=True,
        ),
    )

    # Backfill existing rows using their currently unique
    # Appstle row IDs.
    op.execute(
        """
        UPDATE appstle_subscription_order
        SET source_key = 'id:' || appstle_row_id::text
        WHERE appstle_row_id IS NOT NULL
        """
    )

    # Existing rows are now populated, so make the
    # new natural/source key mandatory.
    op.alter_column(
        "appstle_subscription_order",
        "source_key",
        existing_type=sa.String(length=200),
        nullable=False,
    )

    # Future Appstle rows are allowed to have no numeric
    # source row ID.
    op.alter_column(
        "appstle_subscription_order",
        "appstle_row_id",
        existing_type=sa.BigInteger(),
        nullable=True,
    )

    # appstle_row_id is no longer the unique identifier.
    op.drop_index(
        "ix_appstle_subscription_order_appstle_row_id",
        table_name="appstle_subscription_order",
    )

    op.create_index(
        "ix_appstle_subscription_order_appstle_row_id",
        "appstle_subscription_order",
        ["appstle_row_id"],
        unique=False,
    )

    # source_key becomes the idempotency key.
    op.create_index(
        "ix_appstle_subscription_order_source_key",
        "appstle_subscription_order",
        ["source_key"],
        unique=True,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appstle_subscription_order_source_key'), table_name='appstle_subscription_order')
    op.drop_index(op.f('ix_appstle_subscription_order_appstle_row_id'), table_name='appstle_subscription_order')
    op.create_index(op.f('ix_appstle_subscription_order_appstle_row_id'), 'appstle_subscription_order', ['appstle_row_id'], unique=True)
    op.alter_column('appstle_subscription_order', 'appstle_row_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('appstle_subscription_order', 'source_key')
    # ### end Alembic commands ###
